version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: stew_mil_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: poop
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  basic:
    build: .
    volumes:
      - .:/app
    command: python main.py basic
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: stew_mil_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: poop
      DATABASE_PORT: 5432

  archive:
    build: .
    volumes:
      - .:/app
    command: python main.py archive
    environment:
      DATABASE_HOST: db
      # The rest of the environment variables remain the same as in 'basic'
    depends_on:
      - db

  new:
    build: .
    volumes:
      - .:/app
    command: python main.py new
    environment:
      DATABASE_HOST: db
      # The rest of the environment variables remain the same as in 'basic'
    depends_on:
      - db

volumes:
  pgdata: