version: '3.8'

services:
  db:
    container_name: db_container
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: db # rename to whatever you want the database to be called. Databases contain tables. Militaria is the table name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: poop
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  scraper:
    build: .
    volumes:
      - .:/app
    command: python MILITARIA_SCRAPER_JSON.py # for now this points here but can point to main.py when the structure changes
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: poop
      DATABASE_PORT: 5432

volumes:
  pgdata:
